### PR TITLE
Prefer override VideoPlayer

### PR DESCRIPTION
**Pull request by hudokkow**
VideoPlayer counterpart of https://github.com/xbmc/xbmc/pull/12374

It's only the top commit (https://github.com/garbear/xbmc/pull/83/commits/51d9a00197ab0f402c15567819237ef6c83936d9). The rest is rebase artifacts. Your branch is way behind.

### CODE REVIEW

**Comment by garbear** [comment]
Rebased on lastest `upstream/vpupdates`

**Comment by hudokkow** [comment]
Yeah, moving target.
Better revisit and do it against vpupdates when it stabilizes or PR directly. Thoughts?

**Comment by garbear** [comment]
@hudokkow Can you PR directly to the VP branch? my fixes use the `virtual` keyword which we're getting rid of.

Once the override changes are in I'll refocus my PR to deal with the API issues.

**Comment by hudokkow** [comment]
Okido. I'll pull your branch and update the PR using it as base.
Just need to ask my daughter for permission... ;)

**Comment by garbear** [comment]
I meant skip my branch and send to `vpupdates`.

**Comment by hudokkow** [comment]
Yeap, understood! Already on the third beer...

**Comment by garbear** [comment]
I'd try catching up, but it's 10am here... ;)

**Pull request closed without merging**
