### PR TITLE
Retroplayer 17beta3 cmake tidy up or I'll go nuts...

### PR DESCRIPTION
**Pull request by hudokkow**
Squashed CMake stuff into logical commits and tested on my machine and [jenkins](http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1655/)
It didn't made things worse so... that's a start. :wink:

Please test and let me know about problems other than the ones we know.

### CODE REVIEW

**Comment by garbear** [comment]
Do the libretro cores build? the win32 build size looks a little small.

**Comment by hudokkow** [comment]
Actually this uncovered a CMake syntax error that I never saw in previous builds and (strangely) only manifested now.
Anyway, another [jenkins run](http://jenkins.kodi.tv/job/WIN-32/10246/) shows `game.libretro` and `peripheral.joystick` still build, unlike the other add-ons.
Please don't merge yet. I want to test on my local machine tomorrow.

**Comment by hudokkow** [comment]
Ready to go. https://github.com/garbear/xbmc/pull/65/commits/9a214259ec0ab7cbb587d45e89baaabf4bd85b36 is already in master and will go away after you rebase on beta 4

**Comment by garbear** [comment]
I've cherry-picked these onto my beta 3 branch: https://github.com/garbear/xbmc/commits/retroplayer-17beta3

thanks again!

**Comment by garbear** [comment]
just to verify, we don't need the changes in #56 anymore right?

**Comment by hudokkow** [comment]
Nope, all included and squashed into appropriate commits. You just need the commits present here.

**Comment by garbear** [comment]
cool, and thanks for updating our 63 (!!!) add-ons

**Comment by hudokkow** [comment]
You're welcome!
You still have commits there that aren't needed. Everything with PR56 from fetzerch, PR10257 from me and 2 commits by Montellese can go.

**Comment by hudokkow** [comment]
Now I understand whats going on. You cherry-picked before cleaning those commits and git automatically separates them from this PR.

**Comment by garbear** [comment]
i think i broke something. all add-ons failed:

```

[ 75%] Performing build step for 'yabause'
'mingw32-make.exe' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'call' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

http://jenkins.kodi.tv/job/WIN-32/10338/console

**Comment by hudokkow** [comment]
Uhmm. I see a successful build at http://jenkins.kodi.tv/job/WIN-32/10347/

Something borked?

**Comment by garbear** [comment]
jenkins problem, false alarm. just trying to keep you on your toes

**Comment by hudokkow** [comment]
heheheh!

**Pull request merged**
