### PR TITLE
changed: xbmc.peripheral -> kodi.peripheral

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by notspiff** [comment]
please hold a little, some small leftovers i discovered doing games..

**Comment by notspiff** [comment]
okay, should be fine now. but i need a "no rebase window" if you want them mergeable.

**Comment by garbear** [comment]
merged by hand in 576a6e68a0d9e69852517b6952c9c93dce8ee36c with fixups in aafeae6427abca2eae4a3f4395fe8c810e7c544a

**Comment by notspiff** [comment]
closing.

**Pull request closed without merging**
