### PR TITLE
Retroplayer rename game

### PR DESCRIPTION
**Pull request by notspiff**
it's a bit hard to keep these mergable into a moving target..

### CODE REVIEW

**Comment by garbear** [comment]
sorry, you can PR against the `retroplayer-15alpha1` branch, that one won't be force-pushed and is kept in sync until alpha 2 is released in ten days

otherwise if the PR gets messed up I can just cherry-pick the commits from you

**Comment by notspiff** [comment]
that's the easiest, you can just pick em.

**Comment by notspiff** [comment]
the first commit there is a rebase artifact, assume you got that :)

**Comment by garbear** [comment]
merged by hand in 21e64e8e81d2e6ab16aba2271e56bc49db34c9f5 with fixups in 23184e90a627cacb2a444f670d5004bb5f4e40b9

**Comment by garbear** [comment]
finished the rebrand. something broke, because on both windows and osx I'm seeing this

nestopia grey screen

also, I noticed another bug in game.libretro that is probably related
```
NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.650 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.667 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.667 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.667 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.682 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.682 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.682 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.699 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.699 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.699 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.717 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.718 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.718 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.733 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.733 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.733 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.752 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.752 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.752 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.766 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.766 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.766 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.783 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.783 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.784 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.801 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.802 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.802 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.816 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.816 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.816 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.833 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.834 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.834 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.849 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.849 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.849 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.867 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.867 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.867 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.884 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.884 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.884 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.899 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.899 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.899 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.916 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.916 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.916 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.933 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.934 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.934 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.949 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.950 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.950 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.967 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.967 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.967 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:52.983 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:52.984 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:52.984 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.001 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.001 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.001 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.015 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.016 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.016 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.033 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.033 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.033 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.050 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.050 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.050 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.066 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.066 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.067 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.083 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.083 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.083 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.099 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.100 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.100 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.116 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.117 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.117 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.133 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.133 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.133 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.149 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.150 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.150 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.167 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.168 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.168 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.183 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.183 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.184 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.202 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.202 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.203 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.216 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.217 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.217 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.235 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.235 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.235 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.249 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.249 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.249 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.266 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.266 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.267 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
2015-03-22 21:43:53.283 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_nospritelimit
2015-03-22 21:43:53.284 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_blargg_ntsc_filter
2015-03-22 21:43:53.284 Kodi[41523:1b0f] Debug Print: AddOnLog: NES (Nestopia): Unknown setting ID: nestopia_palette
```

**Comment by garbear** [comment]
confirmed, reverting the settings patch fixes the problem. NES games are playing fine again. marking this rebrand PR as a success

**Pull request closed without merging**
