### PR TITLE
Set hasWidth to true when assigned value to Width

### PR DESCRIPTION
**Pull request by cool-pants**
## Description

Changed the `hasWidth` parameter value allocation to set it to `true` after it is assigned a value.

## Motivation and Context

Before if `hasWidth` was set `false` and `hasRight` had value `true` and `hasLeft` be `true` then the value returned by the `GetDimension` function would be `false` which should be actually `true` since a value has been indeed assigned to `width`.
 
## How Has This Been Tested?

Tested by comparing data obtained from `GetDimensions()` method before and after method in log. The data was tested over four separate skins, namely:
- Estuary
- Estouchy
- Amber
- Confluence

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
The explanation makes sense. I'd be interested to see what problems this causes in the GUI, by demonstrating a problem that is fixed by this change.

Two code comments:

* Assignment on separate lines for git history
* Indentation (watch those tabs) for readability

**Comment by eigendude** [comment]
Every student's right of passage is learning how to make badass PRs. Always proofread your work. You can see the effect of all commits squashed in the Files tab: https://github.com/garbear/xbmc/pull/116/files. In this case there's still a minor readability infraction.

The "How Has This Been Tested?" is blank. This is what I was getting at earlier. How can we test your change?

**Comment by eigendude** [comment]
Sorry work account from my phone

**Comment by cool-pants** [comment]
Can you please clarify what the infraction is, I still can't get it.

Also I am still in process of building the code so I will update the description today.

**Comment by garbear** [comment]
awkward indentation

**Comment by cool-pants** [comment]
Huh it shows perfectly fine on my device.

**Comment by garbear** [comment]
That's because you haven't configured your IDE to show leading and trailing whitespace. See the tab?

Leading whitespace

**Comment by cool-pants** [comment]
Thanks for the help. I fixed it now hopefully.

**Comment by garbear** [comment]
Looks good now. With some test data we can upstream.

**Comment by garbear** [comment]
This is a valid code path optimization. Merging to get in the next test build.

**Pull request merged**
